### ISSUE TITLE
0.2.0 version release checklist

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1173]
- [x] Finish management command refactor
- [ ] Update changelog with all the stuff
 - [x] Django 1.9 and Python 3.5
 - [x] New management command features and structure
 - [x] Multi-database support
 - [x] New way of handling the big downloads to make life easier for smaller computers
 - [x] Hundreds of unique keys, field defs and choices patched by Code Rushers
 - [x] Automatically generated table documentation page
 - [x] .... whatever else ...
- [x] Blog post announcing the updates
- [x] Tag commit in GitHub
- [x] Update setup.py with new version and dependencies (pytz)
- [ ] Push new version to PyPI

**Comment by palewire** [comment]
Aim for Monday AM to get this out.

**Comment by palewire** [comment]
Do we want to include migrations with this?

**Comment by gordonje** [comment]
Excellent question.

I guess the deciding factor is, do we just about have the calaccess_raw models set in stone? Looks like we have 14 outstanding issues related to setting up choice fields. Maybe we would want to bang through those before shipping the migrations with the app.

Are there other kinds of issues that might lead to changes in calaccess_raw's models?

**Comment by palewire** [comment]
Not a ton of things but here's what I can think of:

- [ ] We currently have inconsistent implementation of DateTime versus Date fields and might want to iron that out
- [ ] We are currently using FloatFields in cases where perhaps they should properly be DecimalFields with fixed decimial places
- [ ] We are currently commenting out the withheld address fields, even though CSVs acquired via an off-line records request will have that data and therefore won't load into our system
- [ ] We might have screwed up a data type or NOT NULL declaration

**Comment by gordonje** [comment]
Then I'm inclined to wait. Seems like we would rather be including as few migrations as possible in the package, and if there isn't a compelling need right now, then why not wait until we get through more of that stuff. In the mean time, just run `makemigrations` or `--run-syncdb` after getting the latest changes.
