### ISSUE TITLE
Add choices definitions for all coded fields in the database

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1194]
The database is littered with columns that contain coded values which require a cross walk to understand. For instance, the appearance of ``16001`` in the ``party_cd`` field translates to ``Democrat``.

Our aim is to use Django's [built-in "choices`` field attribute](https://docs.djangoproject.com/es/1.9/ref/models/fields/#choices) to define these codes wherever possible.

Many of these fields have already been given a definition list. But some have not. And some that have been have been incompletely defined.

After #1191 has been completed, we will develop a roadmap towards complete coverage.

For the time being, this ticket can serve as a place to collect and document fields and values that remain undefined.

Here is the current running list of problems that need to be solved.

- [ ] Develop a consistent standard for handling how we document "unknown" values
- [ ] Determine if we want to have a standard text formatting style for all choices, like lowercase or uppercase text. The values are not inconsistently handled.
- [ ] The ``expn_code`` on the ``ExpnCd`` model has dozens of undefined values, as documented in #1165 
- [ ] ``filer_type`` fields across the database remain undefined
- [ ] `interest_cd`` fields across the database remain undefined
- [ ] ``juris_cd`` fields across the database remain undefined, as researched in #969
- [ ] Values from the ``juris_cd`` field on the ``ExpnCd`` table remain undefined, as documented in #237
- [ ] ``stmnt_status`` fields across the database remain undefined and may have a datatype mismatch, as documented in #283 and #256
- [ ] ``link_type`` values remain undefined on the ``FilerLinksCd`` model, as documented in #259
- [ ] ``stmt_type`` fields remain undefined, as documented in #943 and #255
- [ ] Problems reported with values in ``entity_code`` on ``F501502Cd`` model in #240
- [ ] ``status`` fields defined inconsistently in ``FilernameCd`` and the rest of the database, as documented by #251
- [ ] ``form_type`` fields across the database remain undefined, and we need to enforce a consistent definition style if possible, as reported in #228
- [ ] ``form_type`` values remain undefined on ``LoanCd`` model, as documented by #249
- [ ] The Schedule A-1 value of the ``form_type`` on ``RcptCd`` may be misdocumented, as reported by #250

**Comment by stevenrich** [comment]
I'm going to pick this one off.
