### ISSUE TITLE
Adding document references to "campaign" models

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-raw-data#1208]
## Your mission

Add a ``DOCUMENTCLOUD_PAGES`` attribute to a model for one of the state's database tables. 

This will connect our code with [the official government documentation](http://django-calaccess-raw-data.californiacivicdata.org/en/latest/officialdocumentation.html) so we can incorporate it as part of [our expanded version](http://django-calaccess-raw-data.californiacivicdata.org/en/latest/models.html).

## To-do list

According to [our documentation unit tests](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/tests/test_docs.py), the following models in [`campaign.py`](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/campaign.py) lack any reference to [official CAL-ACCESS documentation](http://django-calaccess-raw-data.californiacivicdata.org/en/latest/officialdocumentation.html). 

- [x] Cvr2SoCd
- [x] CvrCampaignDisclosureCd
- [ ] Cvr2CampaignDisclosureCd (Yano)
- [x] RcptCd
- [ ] Cvr3VerificationInfoCd (Michael Keller)
- [x] LoanCd
- [ ] S401Cd (Ben)
- [x] ExpnCd
- [ ] F495P2Cd (Gerald Rich)
- [x] DebtCd
- [x] S496Cd
- [ ] S497Cd (Steven Rich)
- [x] S498Cd

## Here's how

**Step 1:** Claim a model from the to-do list above by leaving a comment below. Tell everyone you're ON IT!

**Step 2**: Open up the file that contains this model. It should be in [calaccess_raw.models.campaign.py](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/campaign.py).

**Step 3**: Hit the little pencil button in the upper-right corner of the code box to begin editing the file.

![Edit](https://dl.dropboxusercontent.com/u/3640647/ScreenCloud/1440367320.67.png)

**Step 4**: Find your model in the file. (Clicking into the box and searching with CTRL-F can help you here.) Once you find it, we expect the model to lack the ``DOCUMENTCLOUD_PAGES`` attribute we want to ensure every model has attached. If it's already there it would look something like this:

```python
@python_2_unicode_compatible
class MyFakeModel(CalAccessBaseModel):
    """
    Blah blah blah.
    """
    UNIQUE_KEY = (
        "WHATEVER",
    )
    DOCUMENTCLOUD_PAGES = [
        DocumentCloud(id='2711614-CalAccessTablesWeb', start_page=21, end_page=22),
    ]
```

A properly configured ``DOCUMENTCLOUD_PAGES`` attribute will contain one or more ``DocumentCloud`` items that specify where this table is explained in the state's official documentation. The links draw their name from the documentcloud.org hosting service where we are republishing the state's source documents, which were provided in PDF format.

If it's already there, the work is already done and you need to pick another model. If it's not, it's going to be your job to add it.

**Step 5:** In a separate tab, open up the <a href="http://www.documentcloud.org/documents/2711614-CalAccessTablesWeb.html#document/p1">official state documentation</a>.

![The docs](https://dl.dropboxusercontent.com/u/3640647/ScreenCloud/1440367001.08.png)

**Step 6:** Find the page the defines your table.

![The definition](https://dl.dropboxusercontent.com/u/3640647/ScreenCloud/1440367068.59.png)

**Step 7:** Note the document's start and end pages as well as the id in the DocumentCloud URL (Hint: It's probably ``2711614``).

**Step 8**: Return to the GitHub tab.

**Step 9**: Add a ``DOCUMENTCLOUD_PAGES`` list that includes points to the pages you just found. If your model is found on pages 200 and 201 of the state documentation linked above, you'd fill add these three lines:

```python
    DOCUMENTCLOUD_PAGES = [
        DocumentCloud(id=2711614, start_page=200, end_page=201),
    ]
```

But indented below the ``UNIQUE_KEY`` of your model like this:

```python
@python_2_unicode_compatible
class MyFakeModel(CalAccessBaseModel):
    """
    Blah blah blah.
    """
    UNIQUE_KEY = (
        "WHATEVER",
    )
    DOCUMENTCLOUD_PAGES = [
        DocumentCloud(id='2711614-CalAccessTablesWeb', start_page=200, end_page=201),
    ]
```

**Step 10**: Scroll down below the code box and describe the change you've made in the commit message. Press the button below.

![Commit](https://dl.dropboxusercontent.com/u/3640647/ScreenCloud/1440367511.66.png)

**Step 11**:  Review your changes and create a pull request submitting them to the core team for inclusion.

![Pull request](https://dl.dropboxusercontent.com/u/3640647/ScreenCloud/1440368058.52.png)

That's it! Mission accomplished!

**Comment by aquintero4354** [comment]
Got CvrCampaignDisclosureCd

**Comment by ryanvmenezes** [comment]
I will take a stab at LoanCd

**Comment by mjenner** [comment]
I've got S498Cd!

**Comment by jayelle-o** [comment]
I've got DebtCd!

**Comment by VigneshRamachandran** [comment]
I got  ExpnCd

**Comment by jernsthausen** [comment]
I got S496Cd

**Comment by mhkeller** [comment]
I got `Cvr2SoCd`

**Comment by geraldarthur** [comment]
I got `F495P2Cd`
