### ISSUE TITLE
Adding document references to choice fields in "campaign" models

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-raw-data#1235]
## Your mission

Add a ``documentcloud_pages`` attribute to a model for one of the choice fields on the campaign tables. 

This will connect our code with [the official government documentation](http://django-calaccess-raw-data.californiacivicdata.org/en/latest/officialdocumentation.html) so we can incorporate it as part of [our expanded version](http://django-calaccess-raw-data.californiacivicdata.org/en/latest/models.html).

## To-do list

According to [our documentation unit tests](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/tests/test_docs.py), the following choice fields in [`campaign.py`](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/campaign.py) lack any reference to [official CAL-ACCESS documentation](http://django-calaccess-raw-data.californiacivicdata.org/en/latest/officialdocumentation.html). 

- [ ] Cvr2SoCd.form_type
- [ ] CvrCampaignDisclosureCd.form_type
- [ ] Cvr2CampaignDisclosureCd.form_type
- [ ] RcptCd.form_type
- [ ] Cvr3VerificationInfoCd.form_type
- [ ] LoanCd.form_type
- [ ] S401Cd.form_type
- [ ] ExpnCd.form_type
- [ ] F495P2Cd.form_type
- [ ] DebtCd.form_type
- [ ] S496Cd.form_type
- [ ] S497Cd.form_type
- [ ] F501502Cd.form_type
- [ ] S498Cd.form_type
- [ ] CvrF470Cd.form_type
- [ ] Cvr2SoCd.off_s_h_c
- [ ] CvrCampaignDisclosureCd.off_s_h_c
- [ ] Cvr2CampaignDisclosureCd.off_s_h_c
- [ ] RcptCd.off_s_h_c
- [ ] S401Cd.off_s_h_c
- [ ] ExpnCd.off_s_h_c
- [ ] S497Cd.off_s_h_c
- [ ] S498Cd.off_s_h_c
- [ ] CvrF470Cd.off_s_h_c
- [ ] CvrSoCd.rec_type 
- [ ] Cvr2SoCd.rec_type 
- [ ] CvrCampaignDisclosureCd.rec_type 
- [ ] Cvr2CampaignDisclosureCd.rec_type 
- [ ] RcptCd.rec_type 
- [ ] Cvr3VerificationInfoCd.rec_type 
- [ ] LoanCd.rec_type 
- [ ] S401Cd.rec_type 
- [ ] ExpnCd.rec_type 
- [ ] F495P2Cd.rec_type 
- [ ] DebtCd.rec_type 
- [ ] S496Cd.rec_type 
- [ ] S497Cd.rec_type 
- [ ] F501502Cd.rec_type 
- [ ] S498Cd.rec_type 
- [ ] CvrF470Cd.rec_type 
- [ ] F501502Cd.party_cd 
- [ ] Cvr2SoCd.sup_opp_c
- [ ] CvrCampaignDisclosureCd.sup_opp_c
- [ ] Cvr2CampaignDisclosureCd.sup_opp_c
- [ ] RcptCd.sup_opp_c
- [ ] S401Cd.sup_opp_c
- [ ] ExpnCd.sup_opp_c
- [ ] S497Cd.sup_opp_c
- [ ] S498Cd.sup_opp_c
- [ ] F501502Cd.elec_type
- [ ] CvrCampaignDisclosureCd.reportnam
- [ ] ExpnCd.expn_code
- [ ] DebtCd.expn_code

## Here's how

**Step 1:** Claim a field from the to-do list above by leaving a comment below. Tell everyone you're ON IT!

**Step 2**: Open up the file that contains this model. It should be in [calaccess_raw.models.campaign.py](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/campaign.py).

**Step 3**: Hit the little pencil button in the upper-right corner of the code box to begin editing the file.

![Edit](https://dl.dropboxusercontent.com/u/3640647/ScreenCloud/1440367320.67.png)

**Step 4**: Find the your field in the file. It will be under the specific model (aka, data table) specified above (Clicking into the box and searching with CTRL-F can help you here.) Once you find it, we expect the field to lack the ``documentcloud_pages`` attribute we want to ensure every model has attached. If it's already there it would look something like this:

```python
@python_2_unicode_compatible
class MyFakeModel(CalAccessBaseModel):
    """
    Blah blah blah.
    """
    UNIQUE_KEY = (
        "WHATEVER",
    )
    # other attributes, including other fields on the model / data table
    your_field = fields.CharField(
        max_length=4,
        db_column="YOUR_FIELD",
        choices=YOUR_FIELDS_CHOICES,
        help_text='Blah blah blah',
        documentcloud_pages=[
            DocumentCloud(id='2756977-Lookup-Codes-Cd', start_page=21, end_page=22),
        ]
    )
```

A properly configured ``documentcloud_pages`` attribute will contain one or more ``DocumentCloud`` items that specify where this table is explained in the state's official documentation. The links draw their name from the documentcloud.org hosting service where we are republishing the state's source documents, which were provided in PDF format.

If it's already there, the work is already done and you need to pick another field. If it's not, it's going to be your job to add it.

**Step 5:** In a separate tab, open up the <a href="https://www.documentcloud.org/documents/2756977-Lookup-Codes-Cd.html">official state documentation</a>.

**Step 6:** Find the pages with useful info about the look-up values.

**Step 7:** Note the document's start and end pages as well as the id in the DocumentCloud URL (Hint: It's probably ``'2756977-Lookup-Codes-Cd'``).

**Step 7**: Return to the GitHub tab.

**Step 8**: Add a ``documentcloud_pages`` list that includes points to the pages you just found. If your model is found on pages 200 and 201 of the state documentation linked above, you'd fill add these three lines:

```python
    documentcloud_pages = [
        DocumentCloud(id='2756977-Lookup-Codes-Cd', start_page=200, end_page=201),
    ]
```

But indented below the field's model and name (as seen in the above example).

**Step 9**: Scroll down below the code box and describe the change you've made in the commit message. Press the button below.

![Commit](https://dl.dropboxusercontent.com/u/3640647/ScreenCloud/1440367511.66.png)

**Step 10**:  Review your changes and create a pull request submitting them to the core team for inclusion.

![Pull request](https://dl.dropboxusercontent.com/u/3640647/ScreenCloud/1440368058.52.png)

That's it! Mission accomplished!

**Comment by LilyMihalik** [comment]
**I'm gonna grab this one** Cvr2SoCd.form_type

**Comment by stevenrich** [comment]
I picked off the last three.

**Comment by palewire** [comment]
This quick SQL query I hacked together will return all of the ``form_type`` values in the campaign models. Before we define a global set of form_type option we should probably integrate the other models files as well.

```sql
SELECT *
FROM (
	SELECT 'CVR_F470_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR_F470_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'S498_CD', "FORM_TYPE", COUNT(*)
	FROM "S498_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'F501_502_CD', "FORM_TYPE", COUNT(*)
	FROM "F501_502_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'S497_CD', "FORM_TYPE", COUNT(*)
	FROM "S497_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'S496_CD', "FORM_TYPE", COUNT(*)
	FROM "S496_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'DEBT_CD', "FORM_TYPE", COUNT(*)
	FROM "DEBT_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'F495P2_CD', "FORM_TYPE", COUNT(*)
	FROM "F495P2_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'EXPN_CD', "FORM_TYPE", COUNT(*)
	FROM "EXPN_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'S401_CD', "FORM_TYPE", COUNT(*)
	FROM "S401_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'LOAN_CD', "FORM_TYPE", COUNT(*)
	FROM "LOAN_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR3_VERIFICATION_INFO_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR3_VERIFICATION_INFO_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'RCPT_CD', "FORM_TYPE", COUNT(*)
	FROM "RCPT_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR2_CAMPAIGN_DISCLOSURE_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR2_CAMPAIGN_DISCLOSURE_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR2_SO_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR2_SO_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR_CAMPAIGN_DISCLOSURE_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR_CAMPAIGN_DISCLOSURE_CD"
	GROUP BY 1, 2
) as form_type_table
ORDER BY 1, 2, 3 DESC
```

**Comment by palewire** [comment]
I just expanded the above query to pull ``form_type`` values from all models where I could find the field. I will run a fresh database installation and then post the values I get back. We can then use that to create a centralied ``FORM_TYPE_CHOICES`` lookup that can be shared among the fields.

```sql
SELECT *
FROM (
	SELECT 'EFS_FILING_LOG_CD', "FORM_TYPE", COUNT(*)
	FROM "EFS_FILING_LOG_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'LPAY_CD', "FORM_TYPE", COUNT(*)
	FROM "LPAY_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'LOTH_CD', "FORM_TYPE", COUNT(*)
	FROM "LOTH_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'LEMP_CD', "FORM_TYPE", COUNT(*)
	FROM "LEMP_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'LCCM_CD', "FORM_TYPE", COUNT(*)
	FROM "LCCM_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'LEXP_CD', "FORM_TYPE", COUNT(*)
	FROM "LEXP_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'LATT_CD', "FORM_TYPE", COUNT(*)
	FROM "LATT_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'F690P2_CD', "FORM_TYPE", COUNT(*)
	FROM "F690P2_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'LOBBY_AMENDMENTS_CD', "FORM_TYPE", COUNT(*)
	FROM "LOBBY_AMENDMENTS_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR_REGISTRATION_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR_REGISTRATION_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR2_REGISTRATION_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR2_REGISTRATION_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR_LOBBY_DISCLOSURE_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR_LOBBY_DISCLOSURE_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR2_LOBBY_DISCLOSURE_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR2_LOBBY_DISCLOSURE_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'TEXT_MEMO_CD', "FORM_TYPE", COUNT(*)
	FROM "TEXT_MEMO_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR_E530_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR_E530_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'SMRY_CD', "FORM_TYPE", COUNT(*)
	FROM "SMRY_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR_F470_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR_F470_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'S498_CD', "FORM_TYPE", COUNT(*)
	FROM "S498_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'F501_502_CD', "FORM_TYPE", COUNT(*)
	FROM "F501_502_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'S497_CD', "FORM_TYPE", COUNT(*)
	FROM "S497_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'S496_CD', "FORM_TYPE", COUNT(*)
	FROM "S496_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'DEBT_CD', "FORM_TYPE", COUNT(*)
	FROM "DEBT_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'F495P2_CD', "FORM_TYPE", COUNT(*)
	FROM "F495P2_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'EXPN_CD', "FORM_TYPE", COUNT(*)
	FROM "EXPN_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'S401_CD', "FORM_TYPE", COUNT(*)
	FROM "S401_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'LOAN_CD', "FORM_TYPE", COUNT(*)
	FROM "LOAN_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR3_VERIFICATION_INFO_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR3_VERIFICATION_INFO_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'RCPT_CD', "FORM_TYPE", COUNT(*)
	FROM "RCPT_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR2_CAMPAIGN_DISCLOSURE_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR2_CAMPAIGN_DISCLOSURE_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR2_SO_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR2_SO_CD"
	GROUP BY 1, 2

	UNION

	SELECT 'CVR_CAMPAIGN_DISCLOSURE_CD', "FORM_TYPE", COUNT(*)
	FROM "CVR_CAMPAIGN_DISCLOSURE_CD"
	GROUP BY 1, 2
) as form_type_table
ORDER BY 1, 2, 3 DESC
```
